[tool.poetry]
name = "iisnalogi"
version = "0.1.0"
description = ""
authors = ["Blazhe_Manev <manev.blazhe@student.um.si>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
